/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#59dbc7",
        "secondary": "#006b5f",
        "surface-container-highest": "#d8e3fb",
        "primary-container": "#0a2540",
        "on-tertiary-fixed": "#001f24",
        "surface-bright": "#f9f9ff",
        "on-primary-fixed-variant": "#314865",
        "on-surface": "#111c2d",
        "outline-variant": "#c4c6ce",
        "surface-variant": "#d8e3fb",
        "inverse-surface": "#263143",
        "tertiary": "#001215",
        "on-secondary-container": "#006f63",
        "tertiary-fixed": "#9eefff",
        "secondary-container": "#76f4e0",
        "on-error": "#ffffff",
        "surface-container": "#e7eeff",
        "on-primary": "#ffffff",
        "background": "#f9f9ff",
        "on-background": "#111c2d",
        "primary-fixed-dim": "#b0c8eb",
        "surface-container-high": "#dee8ff",
        "tertiary-fixed-dim": "#77d4e5",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d2e4ff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "surface-tint": "#49607e",
        "on-primary-container": "#768dad",
        "surface-container-low": "#f0f3ff",
        "surface": "#f9f9ff",
        "inverse-primary": "#b0c8eb",
        "on-error-container": "#93000a",
        "outline": "#74777e",
        "secondary-fixed": "#79f7e3",
        "on-surface-variant": "#43474d",
        "inverse-on-surface": "#ecf1ff",
        "tertiary-container": "#00292f",
        "surface-dim": "#cfdaf2",
        "on-tertiary-fixed-variant": "#004e59",
        "on-primary-fixed": "#001c37",
        "on-tertiary-container": "#3398a8",
        "primary": "#000f22",
        "on-secondary-fixed-variant": "#005047",
        "on-secondary-fixed": "#00201c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-sm": "1rem",
        "space-3xl": "4rem",
        "space-sm": "0.75rem",
        "container-max": "1280px",
        "space-2xs": "0.25rem",
        "space-2xl": "3rem",
        "space-xl": "2rem",
        "gutter-lg": "2rem",
        "gutter-md": "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.5rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "currency-stat": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "currency-stat": ["24px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0.005em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
